### ISSUE TITLE
additional random notes on the startup experience

### ISSUE THREAD

**Issue by mcdurdin** [achille-martin/pyqt-crom#37]
We got the demo app going yesterday. Some notes I took along the way, sorry I don't have more detail:

1. pyqtdeploy was missing from the instructions --> `pip install pyqtdeploy`
2. Qt was installed to ~/Qt, not ~/Qt5.15.2, but QT_DIR was Qt5.15.2 --> `mv ~/Qt ~/Qt5.15.2`
3. ~/.local/bin was not on path for pip modules --> `export PATH=$HOME/.local/bin:$PATH`
4. sip-module and pyqt-builder were missing --> `pip install sip pyqt-builder`

Hope these help!

**Comment by achille-martin** [comment]
Thanks @mcdurdin for your input,

## Good news

The good thing is that all these instructions are actually in the [README](https://github.com/achille-martin/pyqt-crom/blob/main/README.md) under [Getting Started](https://github.com/achille-martin/pyqt-crom/blob/main/README.md#getting-started).

### Pip modules

> pyqtdeploy was missing from the instructions
> ~/.local/bin was not on path for pip modules
> sip-module and pyqt-builder were missing

These are all installed in a python3 virtual environment so that it does not mess up the python package list if anything goes wrong. Additional, if anything does go wrong, one can delete and start again.

The instructions to setup the python3 virtual environment start from [here](https://github.com/achille-martin/pyqt-crom/blob/main/README.md#virtual-environment-setup).

All the python modules required for PyQt-CroM are listed in [requirements.txt](https://github.com/achille-martin/pyqt-crom/blob/main/requirements.txt) and installed in the python3 virtual environment through [this command](https://github.com/achille-martin/pyqt-crom/blob/main/README.md#143-install-the-necessary-pip-packages).

### Qt installation

> Qt was installed to ~/Qt, not ~/Qt5.15.2, but QT_DIR was Qt5.15.2

The Qt folder is set at [this step](https://github.com/achille-martin/pyqt-crom/blob/main/README.md#qt-installation). The reason why it's `~/Qt5.15.2` is so that one can have multiple Qt installations on their machine and select whichever they need.

The instructions are probably not as clear as they should be because the user needs to set the path `$HOME/Qt5.15.2` in the Qt installer directly.

Ultimately, I am trying to create an automatic installer for PyQt-CroM so that any user can setup up their whole machine with one unique `.sh` script for instance. The task is captured [here](https://github.com/achille-martin/pyqt-crom/issues/31), but it's low priority.

## Limitations

Now, if you mention that you had to make some changes while going through the [README](https://github.com/achille-martin/pyqt-crom/blob/main/README.md), it means that the instructions are buried in so much text or not actually clear.
Therefore, I'll need to figure out a way to make them clearer.

In an attempt to make the tutorial a lot clearer, **why do you think you missed the instructions?**

_This will help me focus on the bits that are unclear in the [README](https://github.com/achille-martin/pyqt-crom/blob/main/README.md)._

**Comment by mcdurdin** [comment]
Good to hear. I think we probably lost the venv when we were trying to figure out the issue in #36 -- we started a new shell at some point.

There are a lot of steps in the README; more scripting would probably be the best way to simplify things.

And I guess I just didn't see the option to set the path for Qt in the installer.

One more point of feedback -- my son had been playing with PtQtDeploy before, and the only step that was very difficult was building sysroot.toml -- documentation on how to build that seems very sparse. It's difficult to figure out which modules are required, how to specify them, what the options are. We ended up reading the source which wasn't fun. But this isn't actually any issue on your end. So just for ref.

I'll go ahead and close this.
